removed the usage of !important and added a stylelint that prohibits the usage of !important
ourjapanlife/findadoc-frontend pull request #186
Opened 2021-06-27 11:13 UTC by shoebsd31

## Resolves #184 

_Use the keyword `Resolves` if the PR completes the entire issue or `Part of #[Issue number]` if not"_

### How to test

use npm install and then run 
npx stylelint "**/*.{scss,vue}" to run the linting
the rules can be added/modified in the .stylelintrc.json file

### Screenshots

_Screenshots of the changes working_

2021-06-27 11:57 UTC, Ermish requested changes
Awesome! Thanks for the help! Just need to remove the `package-lock.json` file and we're good!

2021-06-27 11:57 UTC, Ermish commented on package.json
>      "eslint-plugin-vue": "^7.11.1",
please remove the package-lock.json as we are using `yarn` instead of `npm`

2021-06-27 15:13 UTC, ann-kilzer commented
Yes, we're using yarn for this project, so please adjust the instructions.

Otherwise really glad to see this tool addition

2021-06-28 04:13 UTC, ann-kilzer commented on layouts/default.vue
> +
Please avoid adding unnecessary whitespace changes

2021-06-28 04:14 UTC, ann-kilzer commented on pages/about.vue
> +
same here

2021-06-28 04:14 UTC, ann-kilzer commented on assets/variables.scss
> -  color: black !important;
👍🏻

2021-06-28 09:59 UTC, shoebsd31 commented
> Yes, we're using yarn for this project, so please adjust the instructions.
> 
> Otherwise really glad to see this tool addition

Hi Ann, 

I am sorry I didn't understand, which instructions ?

2021-06-29 00:35 UTC, ann-kilzer commented
"How to test" on this ticket references npm.

2021-06-29 09:16 UTC, ermish commented
@shoebsd31 she's referring to this merge request is referencing `npm` instead of `yarn` in the `how to test` section. 

I also noticed the `yarn.lock` seems to point everything to `npm` instead of `yarnpkg`. You might want to undo your changes to the `yarn-lock` file and rerun `yarn` to add your new stylelint reference

2021-07-02 14:23 UTC, shoebsd31 commented
> @shoebsd31 she's referring to this merge request is referencing `npm` instead of `yarn` in the `how to test` section.
> 
> I also noticed the `yarn.lock` seems to point everything to `npm` instead of `yarnpkg`.
> You might want to
> 
> 1. merge the latest changes from `main`
> 2. undo your changes to the `yarn-lock` file
> 3. rerun `yarn` to add your new stylelint reference

got it, I will update the code soon :)

2021-07-04 01:34 UTC, ann-kilzer commented
Closed in favor of #218

2021-07-04 01:34 UTC, closed without merging