Add i18n keys to contrib leads
ourjapanlife/findadoc-frontend pull request #196
Opened 2021-06-27 16:23 UTC by renderf0x

Adds translated strings to about this team section.

### How to test

1. Load about page
2. Change to JP, which has translations in place
(note that the subtitle "our team" is [awaiting merge of a fix from the i18n repo](https://github.com/ourjapanlife/findadoc-localization/pull/75), and is currently falling back to English)

### Screenshots

<img width="377" alt="スクリーンショット 2021-06-28 1 24 30" src="https://user-images.githubusercontent.com/6155643/123552070-70ffe800-d7af-11eb-9708-f11318456a9c.png">

2021-06-27 16:24 UTC, renderf0x commented
Off to bed now but feel free to merge this in if we want it.

2021-06-27 17:00 UTC, ann-kilzer approved these changes
Looking nice, let's fix the merge issues though

2021-06-27 17:21 UTC, theyokohamalife requested changes
I made some changes to the About page so please fix the conflicts when you have a chance.

2021-06-28 00:44 UTC, renderf0x commented
Actually these changes are obviated by the previous PR from LaShawn. I'll close it out.

2021-06-28 00:44 UTC, closed without merging

2021-06-28 05:47 UTC, Ermish commented on pages/about.vue
> +        <h2>{{ $t("about.contributorQ") }}</h2>
Personally, I would recommend we use more than just a letter. 
It looks like a misspell to me 😆 

We could do in a separate PR, as long as we have an issue.