add admin link to toolbar when logged in
ourjapanlife/findadoc-frontend pull request #92
Opened 2021-06-21 12:56 UTC by PsychicNoodles

## Resolves #77 

I'm not super familiar with Vue and wanted to start with something simple, so here's a quick fix to the toolbar that adds a link pointing to the admin dashboard when you're logged in.

### How to test

You should be able to check if you log in as admin and click the toolbar expander.

### Screenshots

I checked the readme, but I couldn't find any instructions on how to try logging into admin locally without a working Firebase API key. If it is written somewhere, I'm sorry I missed it!

Here's a screenshot of the button only when you're logged out, though:

![image](https://user-images.githubusercontent.com/1944082/122764610-9a65d300-d2da-11eb-80bf-2ebe1b968fcf.png)

If there's a preference for another icon then I can switch it out. I just went with something that looked admin-ey 🤔 

(as an aside, it seems the only indication that you failed login is in the console, which is probably good enough but it'd be nice if there was an alert of some kind)

Also, today I learned that the array flattening method in vanilla JS is just called `flat()`.

2021-06-21 14:01 UTC, Ermish approved these changes
LGTM! 
@theyokohamalife do you have a preference on the order of the login, and dashboard buttons? 

I often see the login/out as last in the list and then the dashboard as the first. 🤔

2021-06-21 14:03 UTC, PsychicNoodles commented
Ah, yeah it occurred to me after implementing it that maybe logout should
come after the dashboard link... Whichever way, I can adjust it tomorrow
morning!

On Mon, Jun 21, 2021, 23:02 Philip Ermish ***@***.***> wrote:

> *@Ermish* approved this pull request.
>
> LGTM!
> @theyokohamalife <https://github.com/theyokohamalife> do you have a
> preference on the order of the login, and dashboard buttons?
>
> I often see the login/out as last in the list and then the dashboard as
> the first. 🤔
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ourjapanlife/findadoc-frontend/pull/92#pullrequestreview-688460418>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAO2UESYP5MYYFPLIZNF7FLTT5A57ANCNFSM47BQ5G7A>
> .
>

2021-06-21 14:05 UTC, theyokohamalife requested changes
Thank you so much for adding this! Could you arrange it so the dashboard button appears above the logout?

2021-06-22 00:32 UTC, PsychicNoodles commented
Fixed the order!

2021-06-22 01:41 UTC, Ermish approved these changes
LGTM

2021-06-22 12:29 UTC, PsychicNoodles commented
Is there anything else that is needed here? @theyokohamalife

2021-06-22 23:27 UTC, theyokohamalife approved these changes
LGTM! Thank you so much!!

2021-06-22 23:27 UTC, merged